### ISSUE TITLE
Integrate monaco editor for react

### ISSUE THREAD

**Issue by Saup21** [Saup21/Code-Sandbox#3]
The monaco-editor is a well-known web technology based code editor that powers VS Code. This library handles the setup process of the monaco-editor and provides a clean API to interact with monaco from any React environment. The editor provides Rich IntelliSense, Validation for languages like HTML, CSS, JavaScript, etc which is perfect for our project.

### What to do?
- Go to [monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react)
- Read the docs
- Integrate

`happy coding`

**Comment by chirag3003** [comment]
I want to work on this issue under JWOC

**Comment by Saup21** [comment]
The issue is assigned to you. Happy coding.
