### ISSUE TITLE
Styled the components and added fontsize functionality

### ISSUE THREAD

**Issue by mrudulkolambe** [Saup21/Code-Sandbox#7]
Styled the components and added fontsize functionality
using usestate hook, props and useEffect hook
https://user-images.githubusercontent.com/83169198/151955930-77a186f0-cc5a-42d8-8532-abb2f20bcd7e.mp4

**Comment by Saup21** [comment]
we are gong to have css and javascript as well so font-size is of no use. Monaco editor is going to be used so we need to integrate that first.
